
cloud:
  microservice:
    name: ${MICROSERVICE_NAME:qubership-nifi-registry}
    namespace: ${NAMESPACE:local}

spring:
  main:
    allow-bean-definition-overriding: true
    web-application-type: none
  application:
    name:  ${MICROSERVICE_NAME:qubership-nifi-registry}
    cloud_service_name: ${CLOUD_SERVICE_NAME:qubership-nifi-registry}
    namespace: ${NAMESPACE:local}
    cloud_namespace: ${CLOUD_NAMESPACE:local}
  cloud:
    mvc:
      token-relay:
        enabled: false  # WA for spring boot starting
    consul:
      config:
        prefix: config/${NAMESPACE:local}
        acl-token: ${CONSUL_ACL_TOKEN}
        defaultContext: application
        enabled: ${CONSUL_ENABLED:true}
        watch:
          enabled: ${CONSUL_ENABLED:true}
          delay: 1000
          wait-time: 20
info:
  app:
    name: ${spring.application.name}
    description: qubership-consul-app

policy.update.enabled: false


logging:
  level:
    root: ${ROOT_LOG_LEVEL:INFO}

config:
  file:
    path: ${NIFI_REGISTRY_HOME}/conf/
  main:
    path: ${NIFI_REGISTRY_HOME}/persistent_data/conf/
  notify-completion:
    path: /tmp/
---
spring:
  config:
    activate:
      on-profile: "!development"
    import: consul:${CONSUL_URL}
